"""Add delivery/customer fields to Purchase model

Generated by assistant
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="customer_name",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="phone",
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="source_address",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="destination_address",
            field=models.TextField(null=True, blank=True),
        ),
    ]
