"""Delivery tracking fields for Purchase model.

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_add_delivery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="delivery_lat",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivery_lng",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="source_lat",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="source_lng",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="distance_km",
            field=models.FloatField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="eta_minutes",
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivery_status",
            field=models.CharField(
                max_length=32,
                default="Preparing",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="status_updated_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="delivered_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]

