"""Optional indexes for delivery tracking.

Generated by assistant.
"""
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_delivery_tracking_fields"),
    ]

    operations = []

