# Generated by Django 6.0.6 on 2026-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_coord_fields_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Preparing', max_length=32),
        ),
    ]
